name: Commit
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        elasticsearch:
          - 7.6.2
          - 7.6.1
          - 7.6.0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and test with Maven
        env:
          ELASTICSEARCH_VERSION: ${{ matrix.elasticsearch }}
        run: mvn --batch-mode clean install "-Delasticsearch.version=${{ matrix.elasticsearch }}" --file pom.xml
