name: Commit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elasticsearch:
          - 7.6.2
          - 7.6.1
          - 7.6.0
          - 7.5.2
          - 7.5.1
          - 7.5.0
          - 7.4.2
          - 7.4.1
          - 7.4.0
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and test with Maven
        env:
          ELASTICSEARCH_VERSION: ${{ matrix.elasticsearch }}
        run: mvn clean install -Delasticsearch.version=${ELASTICSEARCH_VERSION} --file pom.xml
