name: Create Release
on:
  push:
    branches: [master]
    tags: ['*']
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        elasticsearch:
          - 7.10.1
          - 7.10.0
          - 7.9.3
          - 7.9.2
          - 7.9.3
          - 7.8.1
          - 7.8.0
          - 7.7.1
          - 7.7.0
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        env:
          ELASTICSEARCH_VERSION: ${{ matrix.elasticsearch }}
        run: |
          mvn --batch-mode clean package \
              -Delasticsearch.version=${{ matrix.elasticsearch }} \
              -Dzentity.version=${{ github.ref }} \
              --file pom.xml
      - run: mkdir -p staging && cp target/releases/*.zip staging
      # Generate the release changelog
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: ${{steps.build_changelog.outputs.changelog}}
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Pull from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`.
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./staging/zentity-${{ github.ref }}-elasticsearch-${{ matrix.elasticsearch }}.zip
          asset_name: zentity-${{ github.ref }}-elasticsearch-${{ matrix.elasticsearch }}.zip
          asset_content_type: application/zip
